"""Conjunction Data Messages, written and read.

Coordinating orbital traffic is not mainly a messaging problem. Operators can
already send each other files. The problem is that a file saying "we will pass
2,491 m from your satellite" is an assertion, and the receiver has no way to
check it without the sender's tooling and the sender's trust.

So the record this module writes carries the state vectors and the manoeuvre,
not just the conclusion, and the reader recomputes the encounter from them with
the same independent verifier the application uses on its own proposals. The
receiving operator does not have to believe the sender's number. They can
disagree with it, and the reader says by how much.

The format is CCSDS CDM keyword-value notation. It is CDM-*shaped* rather than
conforming: a conforming CDM carries a covariance per object and public element
sets do not have one, so no probability appears anywhere. Everything this file
cannot honestly fill in is left out rather than guessed, and the header says so.

Fields outside the standard are namespaced in COMMENT lines as ORION_WEST_*,
which a conforming parser ignores and ours reads.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

import numpy as np

NEWLINE = chr(10)

# CCSDS states positions in kilometres and velocities in kilometres per second.
# Everything inside this application is metres and metres per second, so the
# conversion happens here and nowhere else.
M_PER_KM = 1000.0

EXTENSION_PREFIX = "ORION_WEST_"


class CdmError(ValueError):
    """The message could not be read as a conjunction record."""


@dataclass
class CdmObject:
    designator: str
    name: str
    maneuverable: bool
    r_m: list[float]
    v_mps: list[float]


@dataclass
class CdmEncounter:
    object_designator: str
    tca_s: float
    miss_distance_m: float
    relative_speed_mps: float


@dataclass
class ParsedCdm:
    originator: str
    message_id: str
    created_at: str
    epoch_utc: str
    frame: str
    horizon_s: float
    objects: list[CdmObject]
    encounters: list[CdmEncounter]
    satellite_designator: str
    candidate_id: str = ""
    burn_t_s: float | None = None
    burn_direction: str = ""
    delta_v_mps: float = 0.0
    comments: list[str] = field(default_factory=list)


# --------------------------------------------------------------------- write


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


def _state_lines(r_m, v_mps) -> list[str]:
    return [
        f"X = {r_m[0] / M_PER_KM:.6f} [km]",
        f"Y = {r_m[1] / M_PER_KM:.6f} [km]",
        f"Z = {r_m[2] / M_PER_KM:.6f} [km]",
        f"X_DOT = {v_mps[0] / M_PER_KM:.9f} [km/s]",
        f"Y_DOT = {v_mps[1] / M_PER_KM:.9f} [km/s]",
        f"Z_DOT = {v_mps[2] / M_PER_KM:.9f} [km/s]",
    ]


def write_cdm(snapshot: dict, document: dict | None = None) -> str:
    """Render a case as a CDM the receiver can independently recompute.

    ``document`` is the raw scenario. The case snapshot deliberately strips
    state vectors -- the browser polls it and does not need them -- but a record
    without states can be read and not checked, which is the one thing this
    format exists to avoid. So the states come from the scenario itself.
    """
    scenario = snapshot["scenario"]
    provenance = scenario["provenance"]
    objects = {o["object_id"]: o for o in scenario["objects"]}
    if document:
        for entry in document.get("objects", ()):
            objects.setdefault(entry["object_id"], {}).update(entry)
    satellite_id = scenario["satellite_id"]

    validations = snapshot.get("validations") or []
    chosen = next(
        (v for v in validations if v["status"] == "PASS"),
        validations[-1] if validations else None,
    )

    lines: list[str] = ["CCSDS_CDM_VERS = 1.0"]
    lines += [
        "COMMENT Generated by Orion West. NOT a conforming CDM: no covariance is",
        "COMMENT available from public element sets, so no collision probability",
        "COMMENT is stated anywhere below.",
        "COMMENT Conjunction geometry is synthetic. The primary object orbit is",
        f"COMMENT seeded from NORAD {provenance.get('norad_id')} at its own epoch.",
        "COMMENT State vectors are included so the receiving operator can",
        "COMMENT recompute every figure here rather than take it on trust.",
        f"CREATION_DATE = {_now()}",
        "ORIGINATOR = ORION WEST",
        f"MESSAGE_ID = {snapshot['case_id']}",
        f"COMMENT {EXTENSION_PREFIX}EPOCH = {scenario['epoch_utc']}",
        f"COMMENT {EXTENSION_PREFIX}FRAME = {provenance.get('frame')}",
        f"COMMENT {EXTENSION_PREFIX}HORIZON_S = {scenario['horizon_s']}",
        f"COMMENT {EXTENSION_PREFIX}SATELLITE = {satellite_id}",
        f"COMMENT {EXTENSION_PREFIX}MODEL = {provenance.get('model_version')}",
        "",
    ]

    others = [oid for oid in objects if oid != satellite_id]

    if chosen is None:
        # Nothing has been screened here yet, so the record states no TCA and no
        # miss distance. It still carries the geometry: a receiver who is handed
        # this can screen the encounter themselves and tell us what they find,
        # which is more use than a message saying only that we have not looked.
        lines += [
            "COMMENT No screening has been run for this case yet, so this record",
            "COMMENT makes no claims. The state vectors below are the whole",
            "COMMENT geometry -- screen it yourself and tell us what you get.",
            "",
        ]
        lines += _object_block("OBJECT1", satellite_id, objects, provenance)
        for object_id in others:
            lines += _object_block("OBJECT2", object_id, objects, provenance)
        return NEWLINE.join(lines) + NEWLINE

    lines += [
        f"COMMENT Screening result: {chosen['status']}",
        f"COMMENT Evidence: {chosen['validation_id']}",
        f"COMMENT Screened objects: {', '.join(chosen['screened_objects'])}",
        "COMMENT Independent recomputation agreed with the screening pass to "
        + (
            f"{chosen['max_primary_distance_disagreement_m']:.3e} m."
            if chosen.get("max_primary_distance_disagreement_m") is not None
            else "within tolerance."
        ),
        f"COMMENT {EXTENSION_PREFIX}CANDIDATE = {chosen['candidate_id']}",
    ]

    # The manoeuvre itself, so the receiver reconstructs the same trajectory.
    proposal = snapshot.get("proposal") or {}
    option = _candidate_fields(chosen["candidate_id"])
    if option:
        lines += [
            f"COMMENT {EXTENSION_PREFIX}BURN_T_S = {option['burn_t_s']}",
            f"COMMENT {EXTENSION_PREFIX}BURN_DIRECTION = {option['direction']}",
            f"COMMENT {EXTENSION_PREFIX}DELTA_V_MPS = {option['delta_v_mps']}",
        ]
    else:
        lines.append(f"COMMENT {EXTENSION_PREFIX}BURN = NONE")
    if proposal.get("status"):
        lines.append(f"COMMENT {EXTENSION_PREFIX}PROPOSAL_STATUS = {proposal['status']}")
    lines.append("")

    for encounter in sorted(chosen["encounters"], key=lambda e: e["min_separation_m"]):
        secondary_id = encounter["object_id"]
        lines += [
            "COMMENT ---- relative metadata ----",
            f"COMMENT {EXTENSION_PREFIX}PAIR = {satellite_id}/{secondary_id}",
            f"TCA = {scenario['epoch_utc']} + {encounter['tca_s']:.3f} [s]",
            f"MISS_DISTANCE = {encounter['min_separation_m']:.3f} [m]",
            f"RELATIVE_SPEED = {encounter['relative_speed_mps']:.3f} [m/s]",
            f"COMMENT BOUNDARY_KIND = {encounter['boundary_kind']}",
        ]
        if encounter.get("ambiguous_time"):
            lines.append(
                "COMMENT Minimum is flat; the time is not uniquely determined."
            )
        lines.append("")

        for role, object_id in (("OBJECT1", satellite_id), ("OBJECT2", secondary_id)):
            lines += _object_block(role, object_id, objects, provenance)

    execution = snapshot.get("execution")
    if execution:
        lines += [
            "COMMENT ---- manoeuvre record ----",
            f"COMMENT {EXTENSION_PREFIX}EXECUTION_ID = {execution['execution_id']}",
            f"COMMENT {EXTENSION_PREFIX}EXECUTED_AT = {execution['executed_at_utc']}",
            f"COMMENT {EXTENSION_PREFIX}MODE = {execution['mode']} "
            "(nothing was transmitted to a spacecraft)",
            "",
        ]

    return NEWLINE.join(lines) + NEWLINE


def _object_block(
    role: str, object_id: str, objects: dict, provenance: dict
) -> list[str]:
    """One object's metadata and state vector.

    Written in one place because the reader pairs OBJECT1 with OBJECT2 by
    position; two nearly-identical blocks drifting apart would be a parsing bug
    that only shows up in someone else's software.
    """
    entry = objects.get(object_id, {})
    state = entry.get("initial_state") or {}
    lines = [
        f"OBJECT = {role}",
        f"OBJECT_DESIGNATOR = {object_id}",
        "CATALOG_NAME = " + ("CELESTRAK GP" if role == "OBJECT1" else "SYNTHETIC"),
        f"OBJECT_NAME = {entry.get('name', object_id)}",
        f"EPHEMERIS_NAME = {provenance.get('model_version')}",
        f"MANEUVERABLE = {'YES' if entry.get('kind') == 'SATELLITE' else 'NO'}",
        f"REF_FRAME = {provenance.get('frame')}",
        "COVARIANCE_METHOD = NONE",
    ]
    if state.get("r_m") and state.get("v_mps"):
        lines += _state_lines(state["r_m"], state["v_mps"])
    lines.append("")
    return lines


def _candidate_fields(candidate_id: str) -> dict | None:
    """Burn parameters for an option ID, or None for the no-burn baseline."""
    from backend.planning.candidates import generate_candidates

    for revision in (1, 2):
        for candidate in generate_candidates(revision):
            if candidate.candidate_id == candidate_id:
                if candidate.is_baseline:
                    return None
                return {
                    "burn_t_s": candidate.burn_t_s,
                    "direction": candidate.direction,
                    "delta_v_mps": candidate.delta_v_mps,
                }
    return None


# ---------------------------------------------------------------------- read

_KV = re.compile(r"^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$")
_COMMENT_KV = re.compile(
    rf"^\s*COMMENT\s+{EXTENSION_PREFIX}([A-Z0-9_]+)\s*=\s*(.+?)\s*$"
)
_NUMBER = re.compile(r"-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?")


def _number(text: str, field_name: str) -> float:
    match = _NUMBER.search(text)
    if not match:
        raise CdmError(f"{field_name} is not a number: {text!r}")
    value = float(match.group(0))
    if not np.isfinite(value):
        raise CdmError(f"{field_name} is not finite")
    return value


def parse_cdm(text: str) -> ParsedCdm:
    """Read a CDM back into the pieces needed to recompute it.

    Tolerant of the parts a conforming writer may add and we do not use, strict
    about the parts we need: without state vectors there is nothing to verify,
    and saying so is better than screening a half-built scenario.
    """
    if not text or not text.strip():
        raise CdmError("message is empty")
    if "CCSDS_CDM_VERS" not in text:
        raise CdmError("not a CDM: CCSDS_CDM_VERS is missing")

    extensions: dict[str, str] = {}
    header: dict[str, str] = {}
    comments: list[str] = []
    objects: list[CdmObject] = []
    encounters: list[CdmEncounter] = []

    current: dict = {}
    pending: dict = {}
    pair_secondary = ""

    def close_object() -> None:
        nonlocal current
        if not current:
            return
        if "r_m" not in current or "v_mps" not in current:
            current = {}
            return
        designator = current.get("designator", "")
        if designator and not any(o.designator == designator for o in objects):
            objects.append(
                CdmObject(
                    designator=designator,
                    name=current.get("name", designator),
                    maneuverable=current.get("maneuverable", False),
                    r_m=current["r_m"],
                    v_mps=current["v_mps"],
                )
            )
        current = {}

    axis = {"X": 0, "Y": 1, "Z": 2}

    for raw in text.splitlines():
        extension = _COMMENT_KV.match(raw)
        if extension:
            extensions[extension.group(1)] = extension.group(2)
            continue
        if raw.strip().startswith("COMMENT"):
            comments.append(raw.strip()[7:].strip())
            continue

        match = _KV.match(raw)
        if not match:
            continue
        key, value = match.group(1), match.group(2)

        if key in ("CCSDS_CDM_VERS", "CREATION_DATE", "ORIGINATOR", "MESSAGE_ID"):
            header[key] = value
        elif key == "TCA":
            pending["tca_s"] = _number(value.split("+")[-1], "TCA")
        elif key == "MISS_DISTANCE":
            pending["miss_distance_m"] = _number(value, "MISS_DISTANCE")
        elif key == "RELATIVE_SPEED":
            pending["relative_speed_mps"] = _number(value, "RELATIVE_SPEED")
        elif key == "OBJECT":
            close_object()
            current = {"role": value}
        elif key == "OBJECT_DESIGNATOR":
            current["designator"] = value
            if current.get("role") == "OBJECT2":
                pair_secondary = value
        elif key == "OBJECT_NAME":
            current["name"] = value
        elif key == "MANEUVERABLE":
            current["maneuverable"] = value.strip().upper() == "YES"
        elif key == "REF_FRAME":
            header.setdefault("REF_FRAME", value)
        elif key in axis:
            current.setdefault("r_m", [0.0, 0.0, 0.0])
            current["r_m"][axis[key]] = _number(value, key) * M_PER_KM
        elif key in ("X_DOT", "Y_DOT", "Z_DOT"):
            current.setdefault("v_mps", [0.0, 0.0, 0.0])
            current["v_mps"][axis[key[0]]] = _number(value, key) * M_PER_KM

        # A relative-metadata block is complete once its OBJECT2 is named.
        if (
            key == "OBJECT_DESIGNATOR"
            and current.get("role") == "OBJECT2"
            and {"tca_s", "miss_distance_m"} <= pending.keys()
        ):
            encounters.append(
                CdmEncounter(
                    object_designator=value,
                    tca_s=pending["tca_s"],
                    miss_distance_m=pending["miss_distance_m"],
                    relative_speed_mps=pending.get("relative_speed_mps", 0.0),
                )
            )
            pending = {}

    close_object()

    if not objects:
        raise CdmError(
            "no object carried a state vector; there is nothing to recompute. "
            "A record without X/Y/Z and X_DOT/Y_DOT/Z_DOT can be read but not "
            "verified."
        )

    satellite = extensions.get("SATELLITE") or (
        next((o.designator for o in objects if o.maneuverable), objects[0].designator)
    )

    burn_t = extensions.get("BURN_T_S")
    return ParsedCdm(
        originator=header.get("ORIGINATOR", "unknown"),
        message_id=header.get("MESSAGE_ID", ""),
        created_at=header.get("CREATION_DATE", ""),
        epoch_utc=extensions.get("EPOCH", ""),
        frame=extensions.get("FRAME") or header.get("REF_FRAME", ""),
        horizon_s=float(extensions.get("HORIZON_S", 21600.0)),
        objects=objects,
        encounters=encounters,
        satellite_designator=satellite,
        candidate_id=extensions.get("CANDIDATE", ""),
        burn_t_s=float(burn_t) if burn_t not in (None, "", "None") else None,
        burn_direction=extensions.get("BURN_DIRECTION", ""),
        delta_v_mps=float(extensions.get("DELTA_V_MPS", 0.0) or 0.0),
        comments=comments,
    )


def scenario_from_cdm(parsed: ParsedCdm) -> dict:
    """A scenario document the verifier can screen, built from the record alone.

    Deliberately reconstructed rather than looked up: the point is that the
    message is sufficient on its own, so nothing here reads our own fixtures.
    """
    objects = [
        {
            "object_id": obj.designator,
            "name": obj.name,
            "kind": "SATELLITE" if obj.designator == parsed.satellite_designator else "DEBRIS",
            "maneuverable": obj.designator == parsed.satellite_designator,
            "initial_state": {"r_m": obj.r_m, "v_mps": obj.v_mps},
        }
        for obj in parsed.objects
    ]
    others = [o for o in objects if not o["maneuverable"]]
    if not others:
        raise CdmError("the record names no second object to screen against")

    return {
        "schema_version": 1,
        "scenario_id": f"imported:{parsed.message_id or 'cdm'}",
        "scenario_version": 1,
        "seed": 0,
        "description": f"Reconstructed from a CDM issued by {parsed.originator}",
        "epoch_utc": parsed.epoch_utc or "1970-01-01T00:00:00.000+00:00",
        "horizon_s": parsed.horizon_s,
        "objects": objects,
        "satellite_id": parsed.satellite_designator,
        "primary_threat_id": others[0]["object_id"],
        "known_windows": [],
        "default_policy": {
            "policy_version": 1,
            "max_delta_v_mps": max(parsed.delta_v_mps, 0.2),
            "min_separation_m": 1000.0,
            "blocked_windows": [],
        },
        "provenance": {
            "source_kind": "IMPORTED_CDM",
            "source_url": "",
            "source_sha256": "",
            "norad_id": 0,
            "object_name": parsed.objects[0].name if parsed.objects else "",
            "tle_epoch_utc": parsed.epoch_utc,
            "frame": parsed.frame or "SIM_ECI_TEME_SEEDED",
            "model_version": "two-body-universal-variable-1",
            "synthetic_conjunction": True,
            "note": (
                "Reconstructed from a received CDM. Every figure below is "
                "recomputed here from the state vectors in that message, not "
                "copied from its conclusions."
            ),
        },
    }


# -------------------------------------------------------------------- verify

# The same tolerances the application holds its own two code paths to. A record
# from elsewhere is judged by the standard we judge ourselves by.
AGREEMENT_DISTANCE_TOL_M = 1.0
AGREEMENT_TIME_TOL_S = 0.1


def verify_cdm(text: str) -> dict:
    """Recompute a received record and say whether its claims hold.

    This is what makes the message coordination rather than assertion. The
    sender's conclusions are read only so they can be disagreed with; every
    figure reported back is computed here, from the state vectors they sent,
    by the same verifier that gates our own proposals.
    """
    from backend.planning.candidates import (
        KIND_IMPULSE,
        Candidate,
        baseline_candidate,
    )
    from backend.planning.policy import policy_from_document
    from backend.planning.verifier import validate_candidate

    parsed = parse_cdm(text)
    document = scenario_from_cdm(parsed)
    policy = policy_from_document(document)

    if parsed.burn_t_s is not None and parsed.delta_v_mps > 0:
        candidate = Candidate(
            candidate_id=parsed.candidate_id or "imported",
            kind=KIND_IMPULSE,
            delta_v_mps=parsed.delta_v_mps,
            grid_revision=1,
            burn_t_s=parsed.burn_t_s,
            direction=parsed.burn_direction or "PROGRADE",
        )
    else:
        candidate = baseline_candidate()

    result = validate_candidate(document, policy, candidate)
    recomputed = {e.other_object_id: e for e in result.encounters}

    checks: list[dict] = []
    for claim in parsed.encounters:
        ours = recomputed.get(claim.object_designator)
        if ours is None:
            checks.append(
                {
                    "object_id": claim.object_designator,
                    "agrees": False,
                    "reason": "we found no encounter with this object",
                    "claimed_miss_distance_m": claim.miss_distance_m,
                    "recomputed_miss_distance_m": None,
                }
            )
            continue

        distance_delta = abs(ours.min_separation_m - claim.miss_distance_m)
        time_delta = abs(ours.tca_s - claim.tca_s)
        agrees = (
            distance_delta <= AGREEMENT_DISTANCE_TOL_M
            and time_delta <= AGREEMENT_TIME_TOL_S
        )
        checks.append(
            {
                "object_id": claim.object_designator,
                "agrees": agrees,
                "claimed_miss_distance_m": round(claim.miss_distance_m, 3),
                "recomputed_miss_distance_m": round(ours.min_separation_m, 3),
                "distance_delta_m": round(distance_delta, 6),
                "claimed_tca_s": round(claim.tca_s, 3),
                "recomputed_tca_s": round(ours.tca_s, 3),
                "time_delta_s": round(time_delta, 6),
                "reason": ""
                if agrees
                else (
                    f"the record claims {claim.miss_distance_m:,.1f} m; "
                    f"recomputing from its own state vectors gives "
                    f"{ours.min_separation_m:,.1f} m"
                ),
            }
        )

    disagreements = [c for c in checks if not c["agrees"]]
    return {
        "originator": parsed.originator,
        "message_id": parsed.message_id,
        "created_at": parsed.created_at,
        "frame": parsed.frame,
        "epoch_utc": parsed.epoch_utc,
        "objects": [
            {
                "object_id": o.designator,
                "name": o.name,
                "maneuverable": o.maneuverable,
            }
            for o in parsed.objects
        ],
        "manoeuvre": (
            {
                "candidate_id": candidate.candidate_id,
                "burn_t_s": parsed.burn_t_s,
                "direction": parsed.burn_direction,
                "delta_v_mps": parsed.delta_v_mps,
            }
            if parsed.burn_t_s is not None
            else None
        ),
        "independent_result": {
            "status": result.status,
            "reason_codes": list(result.reason_codes),
            "screened_objects": list(result.evaluated_object_ids),
            "sample_step_s": result.sample_step_s,
            "method": result.method,
            "encounters": [
                {
                    "object_id": e.other_object_id,
                    "min_separation_m": round(e.min_separation_m, 3),
                    "tca_s": round(e.tca_s, 3),
                    "relative_speed_mps": round(e.relative_speed_mps, 1),
                }
                for e in result.encounters
            ],
        },
        "checks": checks,
        "verdict": (
            "NO_CLAIMS"
            if not checks
            else "AGREES"
            if not disagreements
            else "DISAGREES"
        ),
        "note": (
            "Every figure under independent_result was recomputed here from the "
            "state vectors in the message. The sender's conclusions were read "
            "only to compare against."
        ),
    }
